server:
  port: 8888
apollo.bootstrap.enabled: true
#apollo.bootstrap.namespaces: application,application.yaml
apollo:
  meta: http://localhost:8080/
management:
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
conf.url: http://xxxx
#student:
#  sno: 10000
#  teacher:
#    name: 李四
#    gender: 男