smartflow.webservices:
  sg2pboss: http://localhost
  sg2bss1: http://localhost
  sg2bss2: http://localhost
book.price: 89.00
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    enabled: false
spring:
  application:
    name: webservice
