smartflow.webservices:
  sg2pboss: http://192.168.17.36:8101/pboss/services/SG2PBOSSService
logging:
  config: classpath:logback-spring.xml
server:
  port: 8889
spring:
  cloud:
    config:
      discovery:
        service-id: