eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
smartflow.webservices:
  sg2pboss: http://localhost
  sg2bss1: http://localhost
  sg2bss2: http://localhost

server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  application:
    name: webservice
