spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:wangChengChao/conf-repo.git
          skip-ssl-validation: true
        prefix: /config
  freemarker:
    prefer-file-system-access: true
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/