spring:
  cloud:
    config:
      server:
        jdbc:
          sql: SELECT KEY_, VALUE_ FROM PROPERTIES WHERE APPLICATION_=? AND PROFILE_=? AND LABEL_=?
          order: 1
        prefix: /config
server:
  port: 10002

